version: "3.1"

services:
  db:
    container_name: demo-postgres
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_DATABASE: 'demo'
      POSTGRES_USER: 'demo'
      POSTGRES_PASSWORD: 'demo'
    ports:
      - '5555:5432'
    logging:
      driver: none

  demo-service:
    restart: on-failure
    container_name: demo-service
    build: .
    depends_on:
      - db
